package com.cashmemer.print

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.util.Base64
import com.cashmemer.core.data.ReceiptItemCodec
import com.cashmemer.core.model.PaymentType
import com.cashmemer.core.model.Receipt
import com.cashmemer.core.model.ReceiptCategory
import com.cashmemer.core.util.Format
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

/** Which pages of the memo to render. Mirrors the Mass Print Option setting. */
enum class ReceiptPages { PAGE_1, PAGE_2, BOTH }

/**
 * Renders receipts to A4 PDF using the platform PdfDocument — no external
 * library, so nothing extra to keep up to date.
 *
 * Every receipt is two pages by design:
 *
 *  - **Page 1 is the customer's copy.** Their name, what they bought, what
 *    they paid. It deliberately omits their phone, address and the issuing
 *    account, none of which belong on a slip handed across a counter.
 *  - **Page 2 is the shop's record.** Everything, including full customer
 *    contact details, both note fields and the issuing account.
 */
object ReceiptPdfRenderer {

    // A4 at 72 dpi, the unit PdfDocument works in.
    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 42f
    private const val QR_SIZE = 96

    private val brandGreen = Color.rgb(0x2E, 0x6B, 0x1F)

    private val titlePaint = Paint().apply {
        color = brandGreen
        textSize = 22f
        isAntiAlias = true
        isFakeBoldText = true
    }
    private val headingPaint = Paint().apply {
        color = Color.BLACK
        textSize = 13f
        isAntiAlias = true
        isFakeBoldText = true
    }
    private val bodyPaint = Paint().apply {
        color = Color.DKGRAY
        textSize = 11f
        isAntiAlias = true
    }
    private val totalPaint = Paint().apply {
        color = brandGreen
        textSize = 15f
        isAntiAlias = true
        isFakeBoldText = true
    }
    private val rulePaint = Paint().apply {
        color = Color.LTGRAY
        strokeWidth = 0.8f
    }
    private val heavyRulePaint = Paint().apply {
        color = Color.DKGRAY
        strokeWidth = 1.4f
    }

    private const val QTY_COL = 330f
    private const val PRICE_COL = 430f

    suspend fun render(
        context: Context,
        receipts: List<Receipt>,
        pages: ReceiptPages,
        outputFile: File,
    ): Result<File> = withContext(Dispatchers.IO) {
        runCatching {
            val document = PdfDocument()
            var pageNumber = 1

            receipts.forEach { receipt ->
                // Page 2 always renders — it is the shop's record, so it must
                // exist even when both note fields happen to be empty.
                if (pages != ReceiptPages.PAGE_2) {
                    document.newPage(pageNumber++) { drawPageOne(it, receipt) }
                }
                if (pages != ReceiptPages.PAGE_1) {
                    document.newPage(pageNumber++) { drawPageTwo(it, receipt) }
                }
            }

            check(pageNumber > 1) { "Nothing to print" }

            outputFile.parentFile?.mkdirs()
            outputFile.outputStream().use { document.writeTo(it) }
            document.close()
            outputFile
        }
    }

    private inline fun PdfDocument.newPage(number: Int, draw: (Canvas) -> Unit) {
        val info = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, number).create()
        val page = startPage(info)
        draw(page.canvas)
        finishPage(page)
    }

    // ---- Page 1: the customer's copy ---------------------------------------

    private fun drawPageOne(canvas: Canvas, receipt: Receipt) {
        val right = PAGE_WIDTH - MARGIN
        var y = canvas.drawHeader(receipt, "CASH MEMO")

        // Customer name only. Phone, address and the issuing account are the
        // shop's record, not the customer's slip.
        if (receipt.customerName.isNotBlank()) {
            canvas.drawText("Customer: ${receipt.customerName}", MARGIN, y, headingPaint)
            y += 20f
        }

        y = canvas.drawItems(receipt, y)
        y = canvas.drawTotals(receipt, y, right)

        if (receipt.notesPage1.isNotBlank()) {
            y += 16f
            canvas.drawText("Notes:", MARGIN, y, headingPaint)
            y += 15f
            y = canvas.drawWrapped(receipt.notesPage1, MARGIN, y, right - MARGIN, bodyPaint)
        }

        canvas.drawSignature(receipt, PAGE_HEIGHT - MARGIN - 120f)
        canvas.drawQrBlock(receipt)
        canvas.drawText("Generated by Cash Memer", MARGIN, PAGE_HEIGHT - MARGIN, bodyPaint)
    }

    // ---- Page 2: the shop's record -----------------------------------------

    private fun drawPageTwo(canvas: Canvas, receipt: Receipt) {
        val right = PAGE_WIDTH - MARGIN
        var y = canvas.drawHeader(receipt, "CASH MEMO (Page 2)")

        canvas.drawText("Customer Details:", MARGIN, y, headingPaint)
        y += 15f
        listOf(
            "Name" to receipt.customerName,
            "Phone" to receipt.customerPhone,
            "Email" to receipt.customerEmail,
        ).forEach { (label, value) ->
            if (value.isNotBlank()) {
                canvas.drawText("  $label: $value", MARGIN, y, bodyPaint)
                y += 14f
            }
        }
        if (receipt.locationAddress.isNotBlank()) {
            canvas.drawText("  Address: ${receipt.locationAddress}", MARGIN, y, bodyPaint)
            y += 14f
        }
        if (receipt.hasCoordinates) {
            canvas.drawText(
                "  GPS: ${receipt.latitude}, ${receipt.longitude}",
                MARGIN,
                y,
                bodyPaint,
            )
            y += 14f
        }
        y += 8f

        y = canvas.drawItems(receipt, y)
        y = canvas.drawTotals(receipt, y, right)

        // Both note fields, page 2 only — note 2 is the shopkeeper's own.
        listOf("Notes (Page 1)" to receipt.notesPage1, "Notes (Page 2)" to receipt.notesPage2)
            .filter { it.second.isNotBlank() }
            .forEach { (label, text) ->
                y += 16f
                canvas.drawText("$label:", MARGIN, y, headingPaint)
                y += 15f
                y = canvas.drawWrapped(text, MARGIN, y, right - MARGIN, bodyPaint)
            }

        if (receipt.issuerName.isNotBlank() || receipt.issuerEmail.isNotBlank()) {
            y += 18f
            canvas.drawLine(MARGIN, y, right, y, rulePaint)
            y += 16f
            canvas.drawText("Issuer Account:", MARGIN, y, headingPaint)
            y += 15f
            if (receipt.issuerName.isNotBlank()) {
                canvas.drawText("  Name: ${receipt.issuerName}", MARGIN, y, bodyPaint)
                y += 14f
            }
            if (receipt.issuerEmail.isNotBlank()) {
                canvas.drawText("  Email: ${receipt.issuerEmail}", MARGIN, y, bodyPaint)
            }
        }

        canvas.drawSignature(receipt, PAGE_HEIGHT - MARGIN - 120f)
        canvas.drawQrBlock(receipt)
        canvas.drawText(
            "Receipt #${receipt.id} · ${Format.timestamp(receipt.createdAt)}",
            MARGIN,
            PAGE_HEIGHT - MARGIN,
            bodyPaint,
        )
    }

    // ---- Shared blocks ------------------------------------------------------

    /** Title, store, and the meta grid. Returns the next free baseline. */
    private fun Canvas.drawHeader(receipt: Receipt, title: String): Float {
        val right = PAGE_WIDTH - MARGIN
        var y = MARGIN + 18f

        drawText(title, MARGIN, y, titlePaint)
        y += 20f
        drawText(receipt.placeName.ifBlank { "Cash Memer" }, MARGIN, y, headingPaint)

        y += 12f
        drawLine(MARGIN, y, right, y, heavyRulePaint)
        y += 18f

        drawText("Receipt No: #${receipt.id}", MARGIN, y, bodyPaint)
        drawTextRight("Date: ${Format.date(receipt.createdAt)}", right, y, bodyPaint)
        y += 15f

        drawText("Place/Store: ${receipt.placeName}", MARGIN, y, bodyPaint)
        drawTextRight("Time: ${Format.time(receipt.createdAt)}", right, y, bodyPaint)
        y += 15f

        drawText(
            "Category: ${ReceiptCategory.from(receipt.category).label}",
            MARGIN,
            y,
            bodyPaint,
        )
        drawTextRight(
            "Method: ${PaymentType.from(receipt.paymentType).label}",
            right,
            y,
            bodyPaint,
        )
        y += 15f

        drawText("Currency: ${receipt.currencyCode}", MARGIN, y, bodyPaint)
        y += 20f

        return y
    }

    private fun Canvas.drawItems(receipt: Receipt, startY: Float): Float {
        val right = PAGE_WIDTH - MARGIN
        var y = startY

        drawLine(MARGIN, y - 12f, right, y - 12f, heavyRulePaint)
        drawText("Item", MARGIN, y, headingPaint)
        drawTextRight("Qty", QTY_COL, y, headingPaint)
        drawTextRight("Price", PRICE_COL, y, headingPaint)
        drawTextRight("Total", right, y, headingPaint)
        y += 8f
        drawLine(MARGIN, y, right, y, rulePaint)
        y += 16f

        val items = ReceiptItemCodec.decode(receipt.itemsJson)
        items.forEach { item ->
            if (y > PAGE_HEIGHT - 300f) {
                drawText("… more items", MARGIN, y, bodyPaint)
                y += 15f
                return@forEach
            }
            drawText(item.productName.take(46), MARGIN, y, bodyPaint)
            drawTextRight(Format.amount(item.qty), QTY_COL, y, bodyPaint)
            drawTextRight(Format.amount(item.unitPrice), PRICE_COL, y, bodyPaint)
            drawTextRight(
                Format.amountWithCurrency(item.lineTotal, receipt.currencyCode),
                right,
                y,
                bodyPaint,
            )
            y += 15f
        }

        y += 4f
        drawLine(MARGIN, y, right, y, rulePaint)
        return y + 18f
    }

    private fun Canvas.drawTotals(receipt: Receipt, startY: Float, right: Float): Float {
        var y = startY

        drawTotal("Subtotal", receipt.subtotal, receipt.currencyCode, right, y)
        y += 15f

        if (receipt.discount > 0) {
            drawTotal("Discount", -receipt.discount, receipt.currencyCode, right, y)
            y += 15f
        }
        if (receipt.taxPercent > 0) {
            val tax = (receipt.subtotal - receipt.discount).coerceAtLeast(0.0) *
                receipt.taxPercent / 100.0
            drawTotal(
                "Tax (${Format.amount(receipt.taxPercent)}%)",
                tax,
                receipt.currencyCode,
                right,
                y,
            )
            y += 15f
        }

        y += 4f
        drawLine(MARGIN + 260f, y, right, y, heavyRulePaint)
        y += 18f
        drawTextRight("GRAND TOTAL:", PRICE_COL, y, totalPaint)
        drawTextRight(
            Format.amountWithCurrency(receipt.total, receipt.currencyCode),
            right,
            y,
            totalPaint,
        )
        y += 20f

        if (receipt.cashGiven > 0) {
            drawTotal("Cash Given", receipt.cashGiven, receipt.currencyCode, right, y)
            y += 15f
            drawTotal("Change Amount", receipt.changeAmount, receipt.currencyCode, right, y)
            y += 15f
        }

        return y
    }

    private fun Canvas.drawSignature(receipt: Receipt, y: Float) {
        val encoded = receipt.signatureBase64 ?: return
        val bitmap = decodeSignature(encoded) ?: return

        val scaled = Bitmap.createScaledBitmap(bitmap, 180, 70, true)
        val x = PAGE_WIDTH - MARGIN - 180f
        drawBitmap(scaled, x, y, null)
        drawLine(x, y + 74f, PAGE_WIDTH - MARGIN, y + 74f, rulePaint)
        drawText("Authorized Signature", x, y + 88f, bodyPaint)

        scaled.recycle()
        bitmap.recycle()
    }

    /** QR sits bottom-left, clear of the signature block on the right. */
    private fun Canvas.drawQrBlock(receipt: Receipt) {
        val qr = QrRenderer.encode(QrRenderer.payloadFor(receipt), QR_SIZE) ?: return
        drawBitmap(qr, MARGIN, PAGE_HEIGHT - MARGIN - QR_SIZE - 18f, null)
        qr.recycle()
    }

    private fun decodeSignature(base64: String): Bitmap? = runCatching {
        val bytes = Base64.decode(base64, Base64.NO_WRAP)
        BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
    }.getOrNull()

    private fun Canvas.drawTextRight(text: String, right: Float, y: Float, paint: Paint) {
        drawText(text, right - paint.measureText(text), y, paint)
    }

    private fun Canvas.drawTotal(
        label: String,
        amount: Double,
        currency: String,
        right: Float,
        y: Float,
    ) {
        drawTextRight("$label:", PRICE_COL, y, bodyPaint)
        drawTextRight(Format.amountWithCurrency(amount, currency), right, y, bodyPaint)
    }

    /** Naive word wrap — enough for free-text notes. Returns the new baseline. */
    private fun Canvas.drawWrapped(
        text: String,
        x: Float,
        startY: Float,
        maxWidth: Float,
        paint: Paint,
    ): Float {
        var y = startY
        var line = StringBuilder()

        text.split(Regex("\\s+")).forEach { word ->
            val candidate = if (line.isEmpty()) word else "$line $word"
            if (paint.measureText(candidate) > maxWidth) {
                drawText(line.toString(), x, y, paint)
                y += 14f
                line = StringBuilder(word)
            } else {
                line = StringBuilder(candidate)
            }
        }
        if (line.isNotEmpty()) {
            drawText(line.toString(), x, y, paint)
            y += 14f
        }
        return y
    }
}
